### ISSUE TITLE
Can you build the APK for the torguehelper?

### ISSUE THREAD

**Issue by StarChildDK** [Nu3001/xdAuto#2]
The .zip dosent contain a apk :)

Thanks in advance, GREAT WORK!!! I love the xdAuto!

**Comment by jamesgol** [comment]
They are already available at http://xfer.aokp.co/?developer=zaphod&folder=nu3001
Maybe @Zaphod-Beeblebrox would want to include the APK in each of those repositories or in here

**Comment by StarChildDK** [comment]
No they are not, as I wrote, in the zip file, no apk, only the pre build files ;)
