### ISSUE TITLE
CarDoor app enter animation

### ISSUE THREAD

**Issue by jhansche** [Nu3001/xdAuto#9]
The CarDoor app seems to take a snapshot of the current window, and then starts a new window with that old snapshot behind it and the Car Door overlay on top.  But the new window animates in from the side, so it's very distracting.

2 possibilities here:
1. Simply disable the enter animation for MainActivity
2. Switch to more of a "popup" window style. The current Activity approach is very intrusive: if you were in the middle of doing something when the door opens, this screen interrupts whatever you were doing, plus it consumes all the touch events.  If this screen instead were implemented using a PopupWindow (similar to how the transient "Toast" notification works), it can ignore all touches, allowing them to be sent to the application behind the CarDoor app.

**Comment by jhansche** [comment]
Question @jamesgol @Zaphod-Beeblebrox et al:  should this type of issue be opened here, or in each respective repository?  The [readme](https://github.com/Nu3001/xdAuto) says issues should be opened here

**Comment by jamesgol** [comment]
Issues related to general ROM issues should be here, issues related to a piece of existing code should be opened in that repository so the issues can be referenced easily during commits.

**Comment by jhansche** [comment]
OK - I'll move this over to packages_apps_BonovoApps then

To be clear - I'm mainly opening these so I have a reference, and can possibly get input from you and everyone else.  I intend to work on making the changes myself and issuing pull requests.

FWIW, you can still reference issues from commits in another repository by referencing the issue's repository directly.  For example: Nu3001/xdAuto#9 to reference this issue

**Comment by jhansche** [comment]
I tested the change in the linked commit, and it works to at least resolve the awkward transition when showing/hiding the CarDoor screen.

What would be nice (and I'll work on making this change at a later time) is to replace the simple MainActivity screen with instead something like a PopupWindow, which can ignore touch events and allow the windows behind it to show through.

**Comment by jamesgol** [comment]
No other changes required for the simple fix?  If so I'll merge it

**Comment by jhansche** [comment]
Nope, that was it -- adding the attribute to the existing AppTheme is all it takes to turn off the window animations

**Comment by jhansche** [comment]
Fixed at Nu3001/packages_apps_bonovoapps#27
